import { Filesystem, Directory } from '@capacitor/filesystem';
import { Share } from '@capacitor/share';
import { blobToBase64 } from './invoiceGenerator';

/**
 * Handles printing and downloading invoices on the native mobile platform.
 *
 * - Converts the PDF Blob to Base64.
 * - Generates a unique, timestamped filename to prevent repeated-download caching issues.
 * - Saves the file to Directory.Documents via @capacitor/filesystem.
 * - Opens the native system Share Sheet via @capacitor/share, which provides
 *   options to print, save, or share the file (e.g. via WhatsApp).
 *
 * @param {Blob} blob - The PDF Blob object generated by invoiceGenerator.
 * @param {string|number} invoiceNumber - The order number used to name the file.
 * @returns {Promise<{ success: true }>}
 */
export const handleMobileInvoice = async (blob, invoiceNumber) => {
    try {
        // Convert blob to base64
        const base64Data = await blobToBase64(blob);

        // Use a timestamped filename so each action writes a fresh file,
        // preventing any OS/WebView blob URL caching issues.
        const fileName = `invoice_${invoiceNumber}_${Date.now()}.pdf`;

        // Save to the device's Documents directory
        const writeResult = await Filesystem.writeFile({
            path: fileName,
            data: base64Data,
            directory: Directory.Documents,
            recursive: true,
        });

        // Open the native Share Sheet with the saved file URI.
        // The sheet includes native options for printing, saving to Files, WhatsApp, etc.
        await Share.share({
            title: `فاتورة رقم ${invoiceNumber}`,
            url: writeResult.uri,
            dialogTitle: 'مشاركة / طباعة الفاتورة',
        });

        return { success: true };
    } catch (error) {
        // Distinguish between user cancelling the share sheet vs. a real error
        if (
            error &&
            (error.message === 'Share canceled' ||
                (error.message && error.message.toLowerCase().includes('cancel')))
        ) {
            // User dismissed the share sheet — not an error
            return { success: true, cancelled: true };
        }

        console.error('Mobile invoice handler error:', error);
        throw new Error('تعذر تجهيز الفاتورة. يرجى التحقق من أذونات التخزين والمحاولة مرة أخرى.');
    }
};
